services:
  amazon-depo-bot:
    build: .
    container_name: amazon-depo-bot
    restart: unless-stopped
    volumes:
      # Veritabanının konteyner veya repo güncellemelerinde kaybolmaması için Docker Named Volume
      - amazon-data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  amazon-data:
