services:
  amazon-depo-bot:
    build: .
    container_name: amazon-depo-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Veritabanının konteyner veya repo güncellemelerinde kaybolmaması için
      - ./data:/app/data
      - ./proxies.txt:/app/proxies.txt
      - ./categories.txt:/app/categories.txt
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
